site_name: Sostenibilidad
site_url: https://lupastance.github.io/sostenibilidad
theme:
  language: es
  logo: assets/favicon.png
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: pink
      toggle:
        icon: material/brightness-4
        name: 💤 Cambiar a modo oscuro
    
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: 👹 Activar el modo psicópata

  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle

  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - header.autohide
    - content.code.copy
    - toc.integrate
    - content.tooltips

plugins:
  - search:
      lang: es

repo_url: https://github.com/lupastance/sostenibilidad
repo_name: lupastance/sostenibilidad

markdown_extensions:
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/extra.css